### PR TITLE
Fixed critical typo in mods.toml...

### PR DESCRIPTION
**Pull request by realmayus**
...that is crashing the game

### CODE REVIEW

**Comment by LexManos** [comment]
We should REALLY be replacing this value from the build script during packaging. So we don't have to remember to bump it every update.

**Comment by DaemonUmbra** [comment]
This particular issue isn't a version change, looks like an erroneous square bracket being removed.
Also this is the RTD, not the MDK

**Comment by LexManos** [comment]
Ah, read the wrong repo name. Sorry.

**Comment by Aeltumn** [comment]
Oops, this is probably my mistake. Why are you copying the mods.toml from the documentation anyways? There is no difference to the one in the mdk.

**Review by tterrag1098 — APPROVED** [review]

**Pull request merged**
