### PR TITLE
Translate the Documentation to zh_TW (Taiwan)

### PR DESCRIPTION
**Pull request by gkbm2013**
Add a zh_TW (a.k.a. Mandarin or Chinese Traditional) translation.

### CODE REVIEW

**Comment by williewillus** [comment]
Does RTD support multiple languages? Also you just translated the home page, not any of the actual stuff :p

**Comment by LexManos** [comment]
No, also branding with your site/name is not allowed.

**Comment by elifoster** [comment]
[Actually RTD does support multiple languages](https://docs.readthedocs.io/en/latest/localization.html).

**Comment by tterrag1098** [comment]
> This feature only applies to Sphinx documentation.

**Pull request closed without merging**
