### PR TITLE
update branch 1.15.x blockstates page

### PR DESCRIPTION
**Pull request by ghost**
The Blockstates page had some major issues, including incorrect class names and general poor tone.
Changes Made:
* Update IProperty class names from previous incorrect `PropertyType` to correct `TypeProperty`.
* Minor grammatical tweaks and improvements to professionalism in tone.

### CODE REVIEW

**Comment by ghost** [comment]
Fixes #310

**Comment by ghost** [comment]
Speaking frankly, this PR is more of a band-aid than an actual fix. This page really wants to be re-written from scratch, I'm just uncertain exactly how much of a drastic change I should be making.

**Comment by sciwhiz12** [comment]
FYI, a [PR rewriting that page](https://github.com/MinecraftForge/Documentation/pull/288) was submitted by me in May, still awaiting approval.

**Comment by ghost** [comment]
I see. Your PR is of a much larger scope than mine, though I still feel this page warrants a scratch rewrite. @sciwhiz12 do you think I should close this PR in favor of yours?
Also, you've still got one requested change on the PR, check that?

**Comment by sciwhiz12** [comment]
All of the paragraphs that you change are also changed by my PR, so it is safe to close this PR if you wish.

Ah, I haven't requested a review yet. Whoops. But, since Forge 1.16 is incoming, and 1.14.x is going to be unsupported after the inital grace period, I think I'll open a new PR targeting 1.15.x when Forge is stable/has a recommended build.

**Comment by ghost** [comment]
Superceded by #288 
Closed for lack of relevance

**Pull request closed without merging**
