### PR TITLE
Update links from HTTP to HTTPS where possible

### PR DESCRIPTION
**Pull request by ZebulanStanphill**
There were a bunch of links using HTTP to sites that supported HTTPS, so I changed all of them to use HTTPS. Of course, some sites only supported HTTP, so I did not change those.

I also fixed some trailing spaces… or rather, my editor fixed them, and then I noticed it while submitting this PR. So hooray for bonus fixes, I guess? :stuck_out_tongue:

### CODE REVIEW

**Comment by tterrag1098** [comment]
Is this strictly necessary? Do any of these sites not immediately redirect to https?

**Comment by ZebulanStanphill** [comment]
@tterrag1098 http://netty.io does not auto-redirect to https://netty.io. http://files.minecraftforge.net/ also does not auto-redirect to https://files.minecraftforge.net/.

**Comment by tterrag1098** [comment]
Hm, alright. I would rather the whitespace changes were not a part of this PR though, it muddies up the blame down the line.

**Comment by ZebulanStanphill** [comment]
Argh, tried getting rid of the whitespace changes and instead I added more from another whitespace-cleanup-only branch by accident. I'll let you know when I clean it all up.

**Comment by ZebulanStanphill** [comment]
I have removed all whitespace changes from the PR. I created a separate PR for whitespace changes: #188.

**Pull request merged**
