### PR TITLE
Add Information about Vanilla Blockstates

### PR DESCRIPTION
**Pull request by wincinderith**
I ran into this issue because there was no documentation on it. Hopefully this will save someone else the pain I endured trying to figure this out. :)

### CODE REVIEW

**Comment by bonii-xx** [comment]
Property names are resources, all resources need to be lowercase.

**Comment by tterrag1098** [comment]
@bonii-xx I still think this is valid to point out. Personally I don't think of properties as "resources". They are *used* in resources, but aren't resources themselves.

**Comment by bonii-xx** [comment]
They're part of the model resource. I'm not saying it's bad to point it out, But it probably should be pointed out that all resources need to be lowercase.

**Comment by wincinderith** [comment]
@bonii-xx @tterrag1098 How's that?

**Comment by bonii-xx** [comment]
Maybe also add a "this includes the blockstate variant itself, e.g. foobar=baz" the example being a simple enttry from the page.

**Comment by wincinderith** [comment]
@bonii-xx Updated.

**Pull request merged**
