### PR TITLE
Add warning about actual states and TE's

### PR DESCRIPTION
**Pull request by williewillus**
This can cause things like Vazkii/Botania#1999 to happen if you don't do this check

Vanilla does this check in the flower pot itself

### CODE REVIEW

**Comment by diesieben07** [comment]
Oh my this is so ugly... But what can you do.

**Comment by williewillus** [comment]
I'm just puzzled why they thought having getTileEntity mutate the world if it can't find anything be a good idea

**Comment by tterrag1098** [comment]
A getter mutating the world is a fundamental mistake, yes. It would be worthwhile to investigate a forge PR for this issue, but for now this note is probably a good idea.

**Comment by diesieben07** [comment]
What puzzles me is that your workaround even works reliably. A HashMap should explode terribly with multiple threads, even if only one of them writes.

**Comment by tterrag1098** [comment]
@diesieben07 a ChunkCache is only ever accessed from the thread it is created in, though.

**Comment by diesieben07** [comment]
Ah right. I get it now.

**Pull request merged**
