### PR TITLE
Docs for global loot modifiers

### PR DESCRIPTION
**Pull request by Draco18s**
Created some documentation regarding the global loot modifiers system.

Wording adjustments or the order of the subsections can be made, I was doing my best to keep a sensible order to things, but as all three tie together so closely I chose "simplest" to "most complex."

### CODE REVIEW

**Comment by tterrag1098** [comment]
Please target 1.14.x as it is the current active dev branch.

**Comment by Draco18s** [comment]
I had no idea that was the case.

**Comment by zhugeo** [comment]
Documentation is going to be more helpful with this page.

**Comment by Aeltumn** [comment]
@Draco18s Shouldn't you close this PR considering you've made a seperate PR for 1.14?

**Pull request closed without merging**
