### PR TITLE
FG4 / 1.16.5 is using the official mappings

### PR DESCRIPTION
**Pull request by scrouthtv**
So we have to use ~the offical method names~ whatever method names apply instead.

These are the changes I found so far, more to come

EDIT: someone told me that these are not the offical Minecraft mappings, but mcp mappings instead. idk

### CODE REVIEW

**Comment by scrouthtv** [comment]
- [ ] TEs
 - [ ] Items
 - [ ] Models
 - [ ] Rendering
 - [ ] Data Generation
 - [ ] Events
 - [ ] Networking
 - [ ] Data Storage
 - [x] Utilities
 - [ ] Effects
 - [x] Conventions
 - [x] Advanced Topics
 - [x] Contributing to Forge

**Comment by scrouthtv** [comment]
rfc to a maintainer: is this even needed / wanted? Is FG4 targeted by the docs (or still FG3)?

**Comment by TheCurle** [comment]
FG4 is ideal, as FG3 is no longer having major updates.
However, there is an Omnibus PR (#365) in the works that will screw with all this.
I recommend either contributing to that, or holding off on this until that is done.

**Comment by scrouthtv** [comment]
thx

**Comment by scrouthtv** [comment]
Oh yeah it says right there
> Migrating to Mojmaps

**Pull request closed without merging**
