### PR TITLE
Restored files link

### PR DESCRIPTION
**Pull request by xbony2**

### CODE REVIEW

**Comment by Aeltumn** [comment]
The link is supposed to not be where you put it.
You can find the line somewhere in the file:
``[files]: https://files.minecraftforge.net "Forge Files distribution site"`` which defines the link.
~~If you'd click on the link on the documentation site you can it works perfectly fine.~~ _apparently not on 1.15.x_

**Comment by tterrag1098** [comment]
Additionally any pull requests not specific to 1.15.x should be made to the 1.14.x branch.

**Comment by xbony2** [comment]
Screen Shot 2020-02-06 at 5 18 38 PM

This is an issue specific to 1.15. It's fine on 1.14.

**Comment by DaemonUmbra** [comment]
[Oops, looks like I'm the idiot that broke it](https://github.com/MinecraftForge/Documentation/commit/c1ce5701ffb63ae7db036fa4a4b860edc2ab4885?diff=split#diff-2f1cbf017a8b135322ddf705f55c96afL37) and [Aeltumn fixed it on 1.14.x but not 1.15.x](https://github.com/MinecraftForge/Documentation/pull/239/files#diff-2f1cbf017a8b135322ddf705f55c96afR34)

**Comment by xbony2** [comment]
Adjusted link to previous syntax.

**Comment by Aeltumn** [comment]
> 
> 
> [Oops, looks like I'm the idiot that broke it](https://github.com/MinecraftForge/Documentation/commit/c1ce5701ffb63ae7db036fa4a4b860edc2ab4885?diff=split#diff-2f1cbf017a8b135322ddf705f55c96afL37) and [Aeltumn fixed it on 1.14.x but not 1.15.x](https://github.com/MinecraftForge/Documentation/pull/239/files#diff-2f1cbf017a8b135322ddf705f55c96afR34)

I was going to ask @tterrag1098 to merge 1.14.x into 1.15.x after some more PRs were in so things like this would be fixed. Also forgot that this is something that I actually fixed in my PR.

**Comment by turbits** [comment]
yall gonna merge this or what

**Pull request closed without merging**
