### PR TITLE
Minor Out Of Date Information In tileentity.md

### PR DESCRIPTION
**Pull request by AllenSeitz**
I'm a newbie and I could be wrong. But it looks like this file is 10 months out of date.

Under section "Attaching TileEntity to a Block" two functions are specified:

- IForgeBlock#hasTileEntity(IBlockstate state)
- IForgeBlock#createTileEntity(World world, IBlockState state)

But the second function should be IForgeBlock#createTileEntity(IBlockState state, IBlockReader world)

Next in the document "Storing Data within your TileEntity" two more functions are specified:

- TileEntity#writeToNBT(NBTTagCompound nbt)
- TileEntity#readFromNBT(NBTTagCompound nbt)

These functions have since been shortened to "write" and "read". This information is correct on the live website but seems to be wrong in the master branch.

### CODE REVIEW

**Comment by williewillus** [comment]
set the target branch of your PR to 1.13.x not master

**Comment by AllenSeitz** [comment]
Thank you for all the commits! You updated a lot more than just those two parts.

But I seem to be unable to select any other branch other than master? Is it possible that I need access to something before 1.13.x (or any other branch) will show up in the branch pulldown menu? (Typing the name of the branch does not work either.)

**Comment by williewillus** [comment]
actually it doesn't seem like any of the changes you noted in your original post are reflected here. did you push to your own fork and make a PR from that branch?

**Comment by AllenSeitz** [comment]
I actually didn't make any changes myself. I created the PR and you did all of the work.

**Comment by tterrag1098** [comment]
You don't seem to understand what a PR is. Those commits are already merged, see #213 #214 #219. Please don't use PRs to *suggest* changes, just do them.

**Pull request closed without merging**
