### PR TITLE
More block interaction docs

### LINKED ISSUE #94: Needed block interaction methods
<del>I think it would be useful to have lists of "hooks" (not sure what else you'd call them) in relevant pages. For example, the Block page says that it would be too long to document every single event like function. I agree with that. However, I think having a complete list of them with a brief description would not be that difficult and could be incredibly useful. This would also apply for items and anything else with a similarly huge amount of functions like this. </del>

Here is a list of Block Interaction functions that are not documented yet (1.10.2-12.18.3.2254):
* [ ] onBlockDestroyedByPlayer
* [ ] neighborChanged
* [ ] onBlockAdded
* [ ] breakBlock: Done at #103
* [ ] onBlockDestroyedByExplosion
* [x] onBlockActivated
* [ ] onEntityWalk: Done at #103
* [ ] onBlockClicked
* [ ] onEntityCollidedWithBlock
* [ ] onBlockPlacedBy
* [ ] eventReceived
* [ ] onLanded
* [ ] onBlockHarvested
* [ ] removedByPlayer
* [ ] onBlockExploded
* [ ] onPlantGrow

### PR DESCRIPTION
**Pull request by elifoster**
***This PR is not ready! I am submitting it to get feedback on what I currently have and assistance as I go!***

This is to resolve #94 and get rid of those nasty "*Coming Soon!*"s from the block interaction page.

### CODE REVIEW

**Comment by G-Rath** [comment]
I think it would be best to have parameters before return, since that's how it's laid out in JavaDoc, and for `onBlockActivated` currently.

**Comment by elifoster** [comment]
@G-Rath Definitely agree. That's how most doc systems, from what I've seen, lay it out.

**Comment by tterrag1098** [comment]
onEntityWalk is not really what I was thinking about when I wrote in that section header, though I think it does fit. But I think the more often used methods like collision/selection bounds should be higher priority.

**Comment by Akxe** [comment]
Add sideness information about events. Is it server event, client, or both?

**Pull request closed without merging**
