### PR TITLE
Change ITickableTileEntity#update() to tick()

### PR DESCRIPTION
**Pull request by StanCEmpire**
I assume as the docs aren't updated regularly that this may have gotten missed.

### CODE REVIEW

**Comment by tterrag1098** [comment]
This needs to target 1.14.x.

**Comment by StanCEmpire** [comment]
Oops sorry I forked the wrong branch, will target LTS branch in the future 👍

**Comment by StanCEmpire** [comment]
Sorry if I did that wrong, please correct any error I may have made

**Comment by tterrag1098** [comment]
You are now including all 1.15.x commits in your PR, you need to rebase your changes.

**Comment by StanCEmpire** [comment]
So, just to clarify, you want me to rebase my changes from 1.15.x to 1.14.x

If so how would I go about doing that?

Would you like me to make a new PR for 1.14.x?

**Comment by StanCEmpire** [comment]
Closing in favour of https://github.com/MinecraftForge/Documentation/pull/334

**Pull request closed without merging**
